name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 6 horas
    - cron: "0 */6 * * *"
  workflow_dispatch: # Permite execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Baixa o repositório e gera a animação da cobrinha
      - uses: Platane/snk@master
        with:
          github_user_name: andrealtobelli
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Carrega a imagem no repositório
      - name: Commit & Push snake animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
